Add CI/CD

diff --git a/backend/Makefile b/backend/Makefile
--- a/backend/Makefile
+++ b/backend/Makefile
@@ -1,4 +1,4 @@
-MODULES = ./common ./services/api ./services/incident-manager ./services/logger
+MODULES = ./common ./services/api ./services/incident-manager ./services/logger ./services/notifier
 
 .PHONY: lint format
 
@@ -13,14 +13,29 @@ define run_on_modules
 	done
 endef
 
+define get_registry
+	cd ../infra/01-bootstrap && terraform output -raw registry_url
+endef
+
+
 define build_image
     printf "$(YELLOW) Building image for service: $1 with tag: $2$(RESET)\n"; \
-    docker build -f ./services/$1/Dockerfile . -t ${REGISTRY}/alerting-platform-$1:$2
+	REGISTRY=$$($(call get_registry)); \
+	if [ -z "$$REGISTRY" ]; then \
+		echo "Error: Docker registry not found"; \
+		exit 1; \
+	fi; \
+    docker build -f ./services/$1/Dockerfile . -t $${REGISTRY}/alerting-platform-$1:$2
 endef
 
 define push_image
     printf "$(YELLOW) Pushing image for service: $1 with tag: $2$(RESET)\n"; \
-    docker push ${REGISTRY}/alerting-platform-$1:$2
+	REGISTRY=$$($(call get_registry)); \
+	if [ -z "$$REGISTRY" ]; then \
+		echo "Error: Docker registry not found"; \
+		exit 1; \
+	fi; \
+    docker push $${REGISTRY}/alerting-platform-$1:$2
 endef
 
 lint:
@@ -29,12 +44,15 @@ lint:
 format:
 	$(call run_on_modules,  golangci-lint fmt)
 
+test:
+	$(call run_on_modules, go test ./... -v)
+
 bump:
-	@perl -i -pe 's/app_version = "v(\d+)\.(\d+)\.(\d+)"/"app_version = \"v$$1.".($$2+1).".0\""/e' ../infra/terraform.tfvars
-	@sed -i "s/build_time = \".*\"/build_time = \"$$(date '+%Y-%m-%d %H:%M')\"/" ../infra/terraform.tfvars
+	@perl -i -pe 's/app_version = "v(\d+)\.(\d+)\.(\d+)"/"app_version = \"v$$1.".($$2+1).".0\""/e' ../infra/03-helm/terraform.tfvars
+	@sed -i "s/build_time = \".*\"/build_time = \"$$(date '+%Y-%m-%d %H:%M')\"/" ../infra/03-helm/terraform.tfvars
 
 build:
-	@VERSION=$$(grep 'app_version' ../infra/terraform.tfvars | awk -F'"' '{print $$2}'); \
+	@VERSION=$$(grep 'app_version' ../infra/03-helm/terraform.tfvars | awk -F'"' '{print $$2}'); \
 	printf "$(GREEN) Building Docker images with version: $$VERSION$(RESET)\n"; \
 	$(call build_image,api,$$VERSION); \
 	$(call build_image,incident-manager,$$VERSION); \
@@ -42,7 +60,7 @@ build:
 	$(call build_image,notifier,$$VERSION)
 
 push:
-	@VERSION=$$(grep 'app_version' ../infra/terraform.tfvars | awk -F'"' '{print $$2}'); \
+	@VERSION=$$(grep 'app_version' ../infra/03-helm/terraform.tfvars | awk -F'"' '{print $$2}'); \
 	printf "$(GREEN) Pushing Docker images with version: $$VERSION$(RESET)\n"; \
 	$(call push_image,api,$$VERSION); \
 	$(call push_image,incident-manager,$$VERSION); \
diff --git a/frontend/Makefile b/frontend/Makefile
--- a/frontend/Makefile
+++ b/frontend/Makefile
@@ -1,5 +1,24 @@
+.PHONY: lint format build push
+
 lint:
 	@pnpm lint
 
 format:
 	@pnpm format
+
+build:
+	@pnpm build
+
+define get_bucket_name
+    cd ../infra/01-bootstrap && terraform output -raw bucket_name
+endef
+
+push:
+	@TARGET_BUCKET=$$($(call get_bucket_name)); \
+	if [ -z "$$TARGET_BUCKET" ]; then \
+		echo "Error: Bucket name not found"; \
+		exit 1; \
+	fi; \
+	echo "Uploading static files to: gs://$$TARGET_BUCKET"; \
+	gcloud storage cp -r dist/* gs://$$TARGET_BUCKET; \
+	echo "Deployment complete!"
